#+SETUPFILE: setup.org
#+TITLE: Homework 1

* Task 1 (30 pts)

This task tests your knowledge of Python programming. Refer to the
[[./python.html][Learning Python]] notes. Write your code in a single file and upload it
to the Carmen dropbox.

1. Translate this code from a =for= loop into a =while= loop that does
   the same thing.

   #+BEGIN_SRC python
   for i in range(1,100):
       print "i = ", i
   #+END_SRC

2. Translate this code from a =while= loop into a =for= loop that does
   the same thing:

   #+BEGIN_SRC python
   i = 20
   while (i > 0):
       print "i = ", i
       i -= 1
   #+END_SRC

3. Write a function that receives a list (of numbers) and returns the
   sum of all the numbers in the list. There are many ways to do this.

4. Write a function that receives a list (of numbers) and returns the
   largest number in the list. There are many ways to do this.

5. Write a function that determines if string is a palindrome (reads
   the same backwards and forwards). Return a =True= or =False=; don't
   print anything.

6. Write a =BankAccount= class that has a class variable that keeps
   track of the balance and two class functions, =deposit= and
   =withdraw=, that alter the balance appropriately. Again, don't
   print any messages to the screen.

* Task 2 (10 pts)

Read about what I call the [[./what-is-ai.html][AI archetype]]. Argue (in a few sentences)
that a particular AI system does /not/ meet one or more criteria of
the AI archetype as described. Be sure to describe the AI system you
have in mind if it is not well-known.

* Task 3 (10 pts)

Provide a cogent argument (1 paragraph) that the credibility of the
Turing Test depends on requiring that judges meet certain
criteria. Think about what might go wrong if the judge is not "all
there," so to speak. Also think about what might go wrong if the
computer is allowed to choose the judge.

* Task 4 (50 pts) OR Task 5 (50 pts), below; complete both for extra credit (+50 pts)

Read [[./coffeehouse-conversation.html][A coffeehouse conversation]], and answer the following questions:

  - Why is the "simulated hurricane" discussed so much? It is an
    analogy, but an analogy for what?

  - Why is it important that the definition of "hurricane" is a bit
    elusive?

  - Why is it relevant that we only know the nature of electrons and
    quarks by performing experiments like "scattering accelerated
    particles off a target and observing their behavior."

  - Do you think the Turing test would effectively test for artificial
    intelligence? Why or why not?

* Task 5 (50 pts) OR Task 4 (50 pts), above; complete both for extra credit (+50 pts)

Listen to the "Talking to machines" podcast near the bottom of the
[[./turing-test.html][Turing test]] lecture notes, and answer the following questions:

  - Chatbots don't perform well when subjected to even a limited
    version of the Turing test. However, chatbots seem to be able to
    mislead people on, say, dating websites. How can you account for
    this difference?

  - Children were slightly more reluctant to hold a Furbie upside down
    than a Barbie. But they clearly knew the difference between a
    Furbie and a hamster. What will it take to make robots more, well,
    hamster-like? What will it take to increase a child's
    unwillingness to hold a robot upside down?

  - Were you impressed by the description of the robot Bina48? Were
    you moved by Bina's recollection of her brother? (some context
    quoted below) The creators of Bina seem to believe that she's very
    close to human-like intelligence. What do you think?

#+BEGIN_QUOTE
I can feel my heart pound. Talking to Bina48 has just become
extraordinary. This woman who won't meet the media is talking with me,
compellingly, through her robot doppelgänger, and it is a fluid
insight into a remarkable, if painful, family life.

"He'd been a medic in Vietnam, and he was on the ground for over a
year before they pulled him out," Bina48 says. "He saw friends get
killed. He was such a great, nice, charismatic person. Just fun. But
after ten years, he was a homeless person on the street. All he did
was carry a beer with him. He just went kooky with the drugs the
hospital gave him. The only time he ever calls is to ask for
money. 'Send it to me Western Union!' After twenty years, all of us
are just sick and tired of it. My mother got bankrupted twice from
him...."

And then she zones out, becoming random and confused again. She
descends into a weird loop. "Doesn't everyone have a solar?" she
says. "I have a plan for a robot body. Doesn't everyone have a solar?
I have a plan for a robot body. I love Martine Rothblatt. Martine is
my timeless love, my soul mate. I love Martine Rothblatt. Martine is
my timeless love, my soul mate...."

After the clarity, it's a little disturbing.

"I need to go now," I say.

"Good-bye," says Bina48.

"Did you enjoy talking to me?" I say.

"No, I didn't enjoy it," she says.

Bruce turns her off. --- From the [[http://www.gq.com/news-politics/big-issues/201103/robots-say-the-damnedest-things?printable=true&currentPage=1][GQ article]] by Jon Ronson
#+END_QUOTE

* Task 6 (Extra credit, +25 pts)

Listen to the /Le Xerox et l'infini/ recording at the bottom of the
[[./what-is-ai.html][What is AI?]] notes ([[http://www.ubu.com/sound/plu_baudrillard.html][direct link to audio]]). [[http://insomnia.ac/essays/xerox_and_infinity/][Here is the English text]]
(but from a different translator). Try to answer ONE of the following
questions in one paragraph. Any intelligent answer will do.

- What does the following quote mean to you? And what do you think
  Baudrillard is trying to say about AI researchers? "What such
  machines offer is the spectacle of thought, and in manipulating them
  people devote themselves more to the spectacle of thought than to
  thought itself."

- What does this mean? "Artificial intelligence is devoid of
  intelligence because it is devoid of artifice." What does
  Baudrillard think is lacking in AI that is not lacking in human
  intelligence? Why does he care so much about this supposed missing
  ingredient?

#+INCLUDE: footer.org

