#+SETUPFILE: setup.org
#+TITLE: Homework 6

* Task 1 (30 pts)

Read/skim [[http://natcomp.liacs.nl/SWI/papers/cooperative.transport/cooperative.transport.by.ants.and.robots.pdf][Cooperative transport by ants and robots]] (PDF) by Kube and
Bonabeau (2000) ([[http://jmvidal.cse.sc.edu/lib/kube00a.html][full citation]]). Answer the following questions:

  1. What is a suggested solution to the problem of many robots
     communicating with each other?

  2. What are two problems with robot swarms?

  3. How does an ant decide that "group transport" is needed?

  4. How was the "stagnation" problem solved in experiments with
     robots?

* Task 2 (70 pts)

Modify the Shepherds model in NetLogo:

  - Add a new kind of "breed" called a sheepdog. The sheepdogs will
    run around dropping "chemical" (scent) which the sheep will avoid.

  - Program the sheepdogs to move, much like the sheep do.

  - Every time a sheepdog moves, it should leave chemical on the
    "patch" (grid square) that it is currently on.

  - This chemical will diffuse and evaporate. You'll want to look at
    the Ants model in NetLogo and copy how the diffusion and
    evaporation works there.

  - Sheep avoid this chemical (they are scared of the
    sheepdogs). Again, look at the Ants model; in that model, the ants
    go towards the chemical. The sheep, on the other hand, should
    avoid the chemical.

Run some experiments by playing with the number of sheepdogs,
diffusion and evaporation rates, etc. Be sure to add sliders to the
interface to manipulate these parameters.

Turn in your code (the ~.nlogo~ file). If you are not able to transfer
it to Linux, email it to me.

* Extra credit 1 (10 pts)

Load the Wolf Sheep Predation model. Run a BehaviorSpace experiment
(Tools menu, BehaviorSpace). The goal is to find conditions where the
populations are stable. Set some parameter ranges and more than one
repetition. Measure ~count wolves~ and ~count sheep~. Be sure to add
a "Stop condition" like ~count turtles > 5000~ to avoid explosions of
sheep. Also add a time limit like 3000. Create a spreadsheet of the
results. Include this spreadsheet in your homework submission as well
as a written summary of what you observed  (5-7 sentences).

* Extra credit 2 (20 pts)

Create a new strategy for the prisoner's dilemma model called PD Two
Person Iterated. Find the code that starts ~to custom-strategy~ and
modify it. Experiment with your new strategy and report on how well it
works (a few sentences). Provide your new code in your report.

#+INCLUDE: footer.org
