#+SETUPFILE: setup.org
#+TITLE: Homework 10

* Task (100 pts)

Download the visual color "sequence 04" video from the [[http://www.cdvp.dcu.ie/datasets/thermo_visual/][Thermo-Visual
Datasets]] webpage, from Dublin City University. Direct link to video
file: [[http://www.cdvp.dcu.ie/datasets/thermo_visual/balcony4/Balcony4_Vis.mpg][Balcony4\_Vis.mpg]] (74MB MPEG file).

Load this video with OpenCV, perform background subtraction, find the
contours, and their bounding boxes.

This has all been done for you: [[./opencv/track-cpp.zip][track-cpp.zip]] (C++ code and CMake
file), [[./opencv/track.py][track.py]] (Python code), and [[./opencv/track-java.zip][track-java.zip]] (Java project for
Eclipse; requires [[http://code.google.com/p/javacv/][JavaCV]]).

[Note: for JavaCV, you may want to watch these two videos, which cover
installation and creating a simple program: [[http://www.youtube.com/watch?v=b3WUItRh6k8&feature=plcp][Video 1]], [[http://www.youtube.com/watch?v=-RqompUUX2o&feature=relmfu][Video 2]]]

Your primary task, apart from installing OpenCV and making the code
work, is to identify the moving entities with labels like 1, 2, 3,
... You should make a good attempt at connecting the detected blobs
with the correct identities, so that the lady with the purse, for
example, is tracked from the point she enters the scene to when she
leaves.

You won't be able to get perfect tracks. Just make a good attempt. One
approach would be to associate the entity with the nearest identified
entity from the prior frame, and if there is no entity close enough
(and recently enough), make a new id.

Submit your source code to CSE server. You will not be able to test on
the CSE server. Just test on your own machine. Let me know if you
cannot install OpenCV on your own machine.

#+INCLUDE: footer.org
