#+SETUPFILE: setup.org
#+TITLE: Homework 6

* Task 1 (25 pts)

Read/skim [[http://natcomp.liacs.nl/SWI/papers/cooperative.transport/cooperative.transport.by.ants.and.robots.pdf][Cooperative transport by ants and robots]] (PDF) by Kube and
Bonabeau (2000) ([[http://jmvidal.cse.sc.edu/lib/kube00a.html][full citation]]). Answer the following questions:

  1. What is a suggested solution to the problem of many robots
     communicating with each other?

  2. What are two problems with robot swarms?

  3. How does an ant decide that "group transport" is needed?

  4. How was the "stagnation" problem solved in experiments with
     robots?

* Task 2 (25 pts)

Load the AIDS model in NetLogo. Read about it on the Info tab, play
with simulations. Then, answer these questions (as found in the
"Things to try" section of the Info tab):

  1. Run a number of experiments with the GO button to find out the
     effects of different variables on the spread of HIV. Try using
     good controls in your experiment. Good controls are when only one
     variable is changed between trials. For instance, to find out
     what effect the average duration of a relationship has, run four
     experiments with the AVERAGE-COMMITMENT slider set at 1 the first
     time, 2 the second time, 10 the third time, and 50 the last. *How
     much does the prevalence of HIV increase in each case?* *Does
     this match your expectations?*

  2. *Are the effects of some slider variables mediated by the effects
     of others?* For instance, if lower AVERAGE-COMMITMENT values seem
     to increase the spread of HIV when all other sliders are set at
     0, does the same thing occur if all other sliders are set at 10?
     You can run many experiments to test different hypotheses
     regarding the emergent public health effects associated with
     individual sexual behaviors.

* Task 3 (25 pts)

Load the PD N-Person Iterated model in NetLogo. Answer these
questions:

  1. Observe the results of running the model with a variety of
     populations and population sizes. For example, *can you get
     cooperate’s average payoff to be higher than defect’s?* *Can you
     get Tit-for-Tat’s average payoff higher than cooperate’s?* *What
     do these experiments suggest about an optimal strategy?*

  2. Relate your observations from this model to real life
     events. *Where might you find yourself in a similar situation?
     How might the knowledge obtained from the model influence your
     actions in such a situation? Why?*

* Task 4 (25 pts)

Load the Wolf Sheep Predation model in NetLogo. Run a BehaviorSpace
experiment (Tools menu, BehaviorSpace). The goal is to find conditions
where the populations are stable. Set some parameter ranges and more
than one repetition. Measure ~count wolves~ and ~count sheep~. Be sure
to add a "Stop condition" like ~count turtles > 5000~ to avoid
explosions of sheep. Also add a time limit like 3000. Create a
spreadsheet of the results. Include this spreadsheet in your homework
submission as well as a written summary of what you observed (5-7
sentences).


#+INCLUDE: footer.org
