#+SETUPFILE: setup.org
#+TITLE: About the Linux servers

* Accessing the Linux servers

Use the ~ssh~ command (Mac, Linux) or PuTTY ([[http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe][PuTTY EXE download]]) to
access ~stdlinux.cse.ohio-state.edu~ with the username and password
given to you at the beginning of the quarter (check your OSU email).

The CSE department has [[http://www.cse.ohio-state.edu/cs/resources/remote.shtml][some guidance]] for how to remotely access the
Linux servers. Look at the "Unix" section of that page. Wherever is
says ~servername.cse.ohio-state.edu~ or ~facsun.cse.ohio-state.edu~,
use instead ~stdlinux.cse.ohio-state.edu~

Also look at the [[http://www.cse.ohio-state.edu/cs/resources/accounts/credentials.shtml][Usernames & passwords]] section.

* Linux tutorial

Here are some useful videos to help you get up to speed on Linux:

  - [[http://www.youtube.com/watch?v=UhS2f_NqxkY][Basic commands and "nano" editor]] (be sure to mute your speakers)

  - [[http://www.youtube.com/watch?v=Nx4v4XziEHw&feature=related][Basic commands]] (a little more in-depth)

  - [[http://www.youtube.com/watch?v=-WfG_sUz2A8][nano and vi editors]]

  - [[http://www.youtube.com/watch?v=yzahMaUfL4A&feature=related][Creating and compiling a C++ file]]

  - [[http://www.youtube.com/watch?v=rtknqrUbq6M][Creating and compiling a Java file]]

  - [[http://www.youtube.com/watch?v=nwEnzrhtPDc&feature=related][Copying files from your computer to Linux and vice versa]]

* Programming languages

| Language    | Compiler/interpreter command |                  Version |
|-------------+------------------------------+--------------------------|
| C           | ~gcc~                        |                    4.4.6 |
| C++         | ~g++~                        |                    4.4.6 |
| Java        | ~javac~                      |                    1.6.0 |
| FORTRAN     | ~f77~ or ~f95~               | 3.4.6 (f77), 4.4.6 (f95) |
| Common Lisp | ~sbcl~                       |                   1.4.48 |
| Scheme      | ~scheme48~                   |                      1.8 |
| Matlab      | ~matlab~                     |                   R2010b |
| Perl        | ~perl~                       |                   5.10.1 |
| Python      | ~python~                     |                    2.6.6 |
| Ruby        | ~ruby~                       |                    1.9.2 |

If you want to use Java, you must use "subscribe" to it by issuing
this command:

#+BEGIN_EXAMPLE
subscribe
#+END_EXAMPLE

You will see this menu:

#+BEGIN_EXAMPLE
?  #   Package           ?  #   Package           ?  #   Package
-  -   -------           -  -   -------           -  -   -------
   0   ACU-COBOL            7   HOMEBIN              14  OPERATOR      
   1   ADMIN                8   JDK-CURRENT          15  ORACLE        
   2   CONSULT              9   MAGICK-CURRENT       16  PYTHON-3      
   3   DRT                  10  MAPLE11              17  RESOLVE       
   4   EIFFEL               11  MYSQL                18  SML           
   5   FIREFOX              12  OPEN-COBOL-1.0       19  SVN           
   6   FIREFOX-CURRENT       13  OPEN-COBOL-1.1       20  VI            

Enter a command (a,i,q, or h for help), or a number to SUBSCRIBE:
#+END_EXAMPLE

Choose option =8 JDK-CURRENT= (type =8= and press enter). Log out,
then log back in. Now you can use Java.

** Other languages

Email me before you submit an assignment in a different language than
one listed above. You can generally use any language you want as long
as you let me know beforehand.

* Submission instructions

When you are ready to submit files for a homework assignment, run the
~submit~ command like so:

#+BEGIN_EXAMPLE
submit c3521ab hw1 myhw1
#+END_EXAMPLE

This example assumes your files are in the folder ~myhw1~. Note that
each time you submit, your prior submission will be erased.

Always submit an executable version of your code, plus the code
itself. Also, always provide a ~README~ file that tells the grader how
to compile and execute your code.

#+INCLUDE: footer.org
