#+SETUPFILE: setup.org
#+TITLE: Other logics

* Deduction, induction, abduction

Take a basic syllogism:

#+BEGIN_VERSE
All the balls in that urn are red.
This ball is picked from that urn.
---
This ball is red.
#+END_VERSE

We can rewrite it like this:

#+BEGIN_VERSE
$(\forall x)(FromUrn(x) \rightarrow Red(x))$ \\
$FromUrn(y)$ \\
--- \\
$Red(y)$
#+END_VERSE

This is deduction. Given the two premises, the conclusion must
follow. (Technically, modus ponens is being used here.)

If we switch the two assumptions, we naturally get the same
conclusion; it's still a deductive inference.

Now, let's reorganize a little bit differently:

#+BEGIN_VERSE
This ball is picked from that urn.
This ball is red.
---
?
#+END_VERSE

What is the conclusion. Well, nothing follows /deductively/, but let's
be a little more loose about the logic. What if we pick 100 balls and
they're all red. What can we say?

We can say,

#+BEGIN_VERSE
This ball is picked from that urn.
This ball is red.
---
All the balls in that urn are red.
#+END_VERSE

That's induction. Given one (usually many) instances of a phenomenon
(the ball being red after being picked from that urn) can give us
/evidence/ (strong or weak depending on how many tests we perform)
that some /general law/ is in effect. The general law here is, "All
the balls in that urn are red."

Of course, we can test our inductive conclusion (the general law) by
performing more experiments, and ensuring that after each trial, the
law plus the fact that the ball we picked from that urn implies the
ball is red (that is, we test our predictions given by the general
law).

Again, if we reorder the premises, we still have induction.

There is one last reordering:

#+BEGIN_VERSE
All the balls in that urn are red.
This ball is red.
---
?
#+END_VERSE

The missing information now is, where did this ball come from? The
only statement not mentioned is:

#+BEGIN_VERSE
All the balls in that urn are red.
This ball is red.
---
This ball is picked from that urn.
#+END_VERSE

Now we are performing /abduction/ (a term coined by Charles Sanders
Peirce in the early 1900s; note, his name is pronounced like
"purse"). The conclusion is an /explanation/ that gives the /cause/
behind what we have observed (this ball is red).

There is a strong similarity between induction and abduction. Both are
weaker forms of reasoning than deduction (because their conclusions
may be false). However, induction typically requires many experiments
to be a strong conclusion, whereas abduction may have a strong
conclusion from just one instance because abduction typically
describes causal relationships. "This ball is picked from that urn"
/causes/ the ball to be red (with background knowledge that they are
all red in that urn). On the other hand, induction says "they are all
red in that urn," which does not /cause/ the picked ball to be
red. This is a subtle point, so we'll move on (for more information,
read the paper [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.39.6267]["Smart inductive generalizations are abductions"]] by
Josephson).

* Inductive/abductive logic programming

We learned that Prolog...

#+INCLUDE: footer.org
